### ISSUE TITLE
Link to documentation has transposed D and K in URL

### ISSUE THREAD

**Issue by GJKrupa** [sdkman/sdkman-extensions#10]
The link to the SDKMan home in the README file has the URL skdman.io instead of sdkman.io.

**Comment by marc0der** [comment]
Why not raise a PR instead of opening an issue? :-)

**Comment by GJKrupa** [comment]
Happy to do so but I'd still rather raise an issue to track it.  Work habits die hard.

**Comment by marc0der** [comment]
Cool, thanks for the fix!
